/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddDataSource: typeof import('./src/components/dataSource/add-data-source.vue')['default']
    AddPageVariable: typeof import('./src/components/dataSource/add-page-variable.vue')['default']
    copy: typeof import('./src/components/dataSource/addPageVariable copy.vue')['default']
    DataSource: typeof import('./src/components/dataSource/data-source.vue')['default']
    DataSourceCollection: typeof import('./src/components/dataSource/data-source-collection.vue')['default']
    DataSourceCollent: typeof import('./src/components/dataSource/dataSourceCollent.vue')['default']
    EditPageVariable: typeof import('./src/components/dataSource/edit-page-variable.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    'ElButtoncomponents:': typeof import('element-plus/es')['ElButtoncomponents:']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    Environment: typeof import('./src/components/environment/environment.vue')['default']
    EnvironmentList: typeof import('./src/components/environment/environment-list.vue')['default']
    Header: typeof import('./src/components/header/header.vue')['default']
    Layout: typeof import('./src/components/layout/layout.vue')['default']
    LcButton: typeof import('./src/ui-lib/lc-button.vue')['default']
    Link: typeof import('./src/ui-lib/lc-link/link.vue')['default']
    ProjectName: typeof import('./src/components/header/project-name.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabCard: typeof import('./src/ui-lib/tab-card/tab-card.vue')['default']
    TabLink: typeof import('./src/ui-lib/tab-card/tab-link.vue')['default']
  }
}
